### ISSUE TITLE
Not work anymore

### ISSUE THREAD

**Issue by zyndin** [jsososo/music-player#1]
It seems QQ update host or source link. And then all songs are not working anymore.

Btw thank you so much.

**Comment by jsososo** [comment]
Yes, at the same time, Tencent has updated some api, and I've fixed them.



发自我的小米手机
在 zyndin <notifications@github.com>，2019年3月21日 00:23写道：

It seems QQ update host or source link. And then all songs are not working anymore.

Btw thank you so much.
